### ISSUE TITLE
Integrate with asp.net

### ISSUE THREAD

**Issue by ccaiolopes** [akveo/blur-admin#10]
Hello,

I would like to integrate the theme with asp.net MVC, but I can not separate the layers, do not know which file is the server side and client side is which.

Can you help me ? Thank you.

**Comment by lugovsky** [comment]
@ccaiolopes This is just HTML template, so you can consider each file in it as client-side.

In any case our build is based on this generator https://github.com/Swiip/generator-gulp-angular/. So regarding file structure you can refer to its docs
