### ISSUE TITLE
Add sidebar items dynamically from controller

### ISSUE THREAD

**Issue by vijaywm** [akveo/blur-admin#104]
Is it possible to add the ability to add sidebar items on route activation? I have created an abstract route the gets the menu items to be shown to user dynamically after login

**Comment by vazh** [comment]
https://akveo.github.io/blur-admin/articles/051-sidebar/

it's in the documentation.
```javascript
baSidebarServiceProvider.addStaticItem({
      title: 'Menu Level 1',
      icon: 'ion-ios-more',
      .....: .......
});
```
the configuration is there.

**Comment by ShankzPatil** [comment]
check solution here: https://github.com/akveo/blur-admin/issues/141

**Comment by coreboarder** [comment]
How would one dynamically create submenu links with this?
