### ISSUE TITLE
Any plans using angular component router

### ISSUE THREAD

**Issue by suricactus** [akveo/blur-admin#105]
Do you have any plans moving to component router instead of ui-router?

**Comment by nnixaa** [comment]
Hey @suricactus, not at the moment, may I ask you why you have an interest in having it based on component router over ui-router? Thanks.

**Comment by josephbisaillon** [comment]
@suricactus component router is deprecated anyways, angular has recommended ngRoute or ui-router has the alternatives.

https://docs.angularjs.org/guide/component-router

**Comment by suricactus** [comment]
A week or two after I asked my question component-router became deprecated. This issue is not relevant since then.
