### ISSUE TITLE
Accordion panel

### ISSUE THREAD

**Issue by tanahara** [akveo/blur-admin#11]
I am trying to make a basic panel (the transparent one not bootstrap) with accordion functionality. I cannot get the actual panel to change from bootstrap white to blur themed clear.

```
<uib-accordion>
    <uib-accordion-group is-open="true" heading="Bosses" panel-class="accordion-panel" >
```

**Comment by lugovsky** [comment]
Hi!

unfortunately we don't support bootstrap accordion panels. The reason for that is because we need a little javascript for panels to be blurry (not transparent! note it :) ). You can look inside of directives `baPanel` and `baPanelBlur` for more information.

Anyway feel free to provide PR :)

**Comment by tanahara** [comment]
Understood, thanks :)
