### ISSUE TITLE
gulp build problem

### ISSUE THREAD

**Issue by ggunders** [akveo/blur-admin#111]
this is a really odd one. forgive for asking.

what would cause the generated index.html to include vendor.css and vendor.js. 

ive built the project in a standalone directory just fine with the autogenerated vendor-309303 css/js. however when i copy the src dir, bower.json, pakcage.json into a spring server project the build tasks look like they all complete just fine. however, there are two files that cannot be found by the brower when running under spring server(vendor.css and vendor.js)

the other js and css files are good, they can be found by the browser.

why would one folder work and another one not work. tried npm clean and install, rebuild node-sass, ensured the exact gulp files are the same.... lost

thx

**Comment by ggunders** [comment]
ok i believe this is actually a bug now. i think.

project builds fine as long as the src and dst directories are on equal level with each other.

setup a empty dir structure like this

project/
src/main/srcapp
src/main/webapp

put all source files in the srcapp directory
change the gulp/conf.js to this

exports.paths = {
  src: 'src/main/srcapp',
  dist: 'src/main/webapp',
  devDist: 'dev-release',
  tmp: '.tmp',
  e2e: 'e2e'
};


the gulp build process generates different builds and a different index.html

easy to replicate

**Comment by ggunders** [comment]
this is definitely a issue with gulp paths not being in the same directory level. if you move the source or the dest directory away from the main level the inject.js build script does not find all the injections. assistance greatly appreciated. thanks

**Comment by vazh** [comment]
why did you copy src too ?

you only need files inside dist folder if you already build it

**Comment by ggunders** [comment]
I'll comment more soon. 

Basically I put source in 
Src/main/sourcespp

Told build script to put build files in 
Src/main/webapp

Gulp build will complete w o error and place most of the files in dest directory. However, not all js css maps will be generated. The index injections are different when the src and dest paths are in different hierarchies. Tried numerous scenarios where the paths are not on the same level. 

Can't split the src and dest directories. 

I can provide more logs

**Comment by vazh** [comment]
Try gulp serve:build

If no error generated then you need to find another way to work it out

**Comment by ggunders** [comment]
This is super easy to replicate, im hoping someone could grab the project and move the src directory down one level, change the conf.js to reflect the change and build the project. its a different build result. The build is not picking up the vendor scripts or the css. 

ensuring a agnostic build process seems legit as not all project users are going to have the source and dest paths in the root of the project. 

gulp serve:build is not a task

gulp serve works because its picking all the files from dest, .tmp, /serve

gulp build doesnt generate a build that another webserver can use due to the missing js, css injects.

I am new to using gulp, im hoping someone can try this quick test. after build, just look at the index.html injections. there are half the number of injections as there should be if you move the src directory away from project root. thx

**Comment by ggunders** [comment]
ok after lots of debug work on the build scripts, trying to learn gulp i found that the index.html file is what actually tells the build script where to inject to /from. if you move your directories from the root location make sure you update the index.html <build> paths.

**Comment by vazh** [comment]
well, gulp did inject the path of those js/css into index.html

**Comment by ggunders** [comment]
closing this as modifications to index.html was key

**Comment by msegeya** [comment]
Hi  guys,

I am facing a similar challenge as ggunders mentioned, can you please specify where exactly is that path that you are referring,that  have  to be changed/updated ?
