### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by lepatlamass** [akveo/blur-admin#12]
npm WARN deprecated gulp-clean-css@1.0.2: unnecessary duplicate of gulp-minify-css
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lepat\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.3.12
npm ERR! file C:\Users\lepat\AppData\Roaming\npm-cache\pinkie-promise\1.0.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\lepat\AppData\Roaming\npm-cache\pinkie-promise\1.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:

**Comment by lepatlamass** [comment]
having error in npm install
1-first telling me that gulp-clean-css is duplicated which is not,
2-asking me to see the original master of the project that is not a json file.
thanks for your help

**Comment by lugovsky** [comment]
Most possibly this is environment problem.

Looks like package pinkie-promise in cache of your NPM has broken package.json file

I would suggest to reinstall that package
