### ISSUE TITLE
Working with File Upload

### ISSUE THREAD

**Issue by awii5** [akveo/blur-admin#120]
Hello,

I am trying local image upload  and displaying the same.

Have created folder as follows : **blur-admin\src\app\fileUpload**  where i want to save uploaded images.

Please find the attach code for your reference. 

[script.txt](https://github.com/akveo/blur-admin/files/368617/script.txt)

Its giving me error as http://localhost:3000/src/app/fileUpload 404 (Not Found).

Please suggest the proper way to achieve the task.

Thanks & Regards,
Anuprita.

**Comment by vazh** [comment]
angular is client side scripting, so its only in the browser.
it cannot upload files locally by itself.

**Comment by nnixaa** [comment]
Hey @awii5, as @vazh stated you first of all need to have a back-end part which handles the file and saves it to a proper location on your web-server. Without a back-end you won't be able to upload a file.
