### ISSUE TITLE
How Access im my Sever Without gulp server?

### ISSUE THREAD

**Issue by jeanrl** [akveo/blur-admin#121]
I put all files em my vps but if not run without gulp server, how fix this?

Thanks.

**Comment by vazh** [comment]
put it inside apache/nginx, just like you usually put your html/css/js files.
but run `gulp build` first. then copy the files inside release folder into apache/nginx

**Comment by nnixaa** [comment]
@jeanrl as @vazh correctly suggested, you just need to build the project first, then put the result of the build (html/css/images files) to a web server root (depends on what kind of web server you use). Let us know if you have any questions.

**Comment by Shivadhar18** [comment]
+1
