### ISSUE TITLE
conflict with angular-material datepicker

### ISSUE THREAD

**Issue by chouex** [akveo/blur-admin#126]
problem opening datepicker dialog when the page scrolled in IE

the reason is the angular-material use body scrollTop to calculate offset, the angular demo page is scrolling only  the content but blur-admin is scrolling whole body

https://material.angularjs.org/latest/demo/datepicker

example page in blur-admin
```
<div class="widgets">
<div style="height: 1500px;"></div>
    <md-content>
        <h4>Standard date-picker</h4>
        <md-datepicker ng-model="myDate" md-placeholder="Enter date"></md-datepicker>
    </md-content>

</div>
```
bower install angular-material

is it possible scrolling the content instead of scrolling whole body in blur-admin?

    "angular-material": "^1.0.9"
InternetExplorer:11

**Comment by vazh** [comment]
only in IE ? how about chrome/FF.

**Comment by chouex** [comment]
in https://ajax.googleapis.com/ajax/libs/angular_material/1.0.7/angular-material.js
function disableBodyScroll() 

chrome: body.scrollHeight = body.clientHeight  
IE: body.scrollHeight > body.clientHeight  

i think this is the different between chrome and IE

so IE will set top of body <0

**Comment by chouex** [comment]
i scroll the `main` element instead if body fixed the problem.
```
html, body {
  overflow: hidden;
}

main{
  overflow: auto;
  height: 100%;
}
