### ISSUE TITLE
Gulp serve issue

### ISSUE THREAD

**Issue by code-blooded-developer** [akveo/blur-admin#128]
I have installed all packages with npm install but when I run gulp serve it throws Bus error (core dumped).

[15:48:11] Using gulpfile ~/Projects/blur-admin/gulpfile.js
[15:48:11] Starting 'scripts'...
[15:48:14] Starting 'styles'...
Bus error (core dumped)

**Comment by vazh** [comment]
does npm install completed ? or did it run into an error ?

try delete your `node_modules` & `bower_components` folder. and then try running `npm install` again

**Comment by harishmohanani** [comment]
i am getting this error while npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN blur_admin@1.2.0 No repository field.
npm WARN blur_admin@1.2.0 No license field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/harish/Projects/blur-admin/npm-debug.log

**Comment by vazh** [comment]
@harishmohanani try upgrading your npm
`npm install -g npm`

**Comment by harishmohanani** [comment]
@vazh 
not helping 
still getting the same error

**Comment by akigupta131** [comment]
1. `sudo npm cache clean -f `(force) clear you npm cache
2. `sudo npm install -g n` install "n" (this might take a while)
3. `sudo n stable` upgrade to lastest version

After update, check with `node -v`
This answer solved the issue

Picked up from:-
https://davidwalsh.name/upgrade-nodejs
