### ISSUE TITLE
Support for ES6

### ISSUE THREAD

**Issue by vijaywm** [akveo/blur-admin#130]
Is it possible to include support for ES6 in the build pipeline ? That will help in adding new modules with the ES6 class structure.
I have been trying ES6 controllers along with gulp-babel to build, but cannot get it going

**Comment by vijaywm** [comment]
I have ported over your template to Webpack. Everything is almost ok, except there is some resizing issue, so the page-top loads where in the middle of the page and the al-content does'nt resize correctly on window resize. any idea what I might be missing. 
Could it be the sequence to loading scripts ? Could you give some pointers on where to look?
![blur-admin](https://cloud.githubusercontent.com/assets/4676890/17179321/65b1920c-5436-11e6-9833-9f6e00f4df64.jpg)

**Comment by vijaywm** [comment]
Ok. The problem was that I was including the 404.scss. Works fine after removing 404.scss.

**Comment by Disorrder** [comment]
@vijaywm could you share your example? I've started this way too, but without success. Did you change gulpfile or use Webpack without gulp? How did you bundle all existing scripts?

**Comment by vijaywm** [comment]
@Disorrder I have used the template from [here](https://github.com/sJhonny-e/extended-angular-starter)

1. Copy the app folder from the BA template into the above template. 
2. Remove all the BA modules under app/pages and add your new modules.

The only changes required were - 

**added an index.js under themes that imports all the BlurAdmin js files under theme**
```
....
import './theme.module'
import './theme.config'
import './theme.constants'
import './theme.configProvider'
import './theme.service'
import './theme.run'
...
const module = angular.module('themeloader', ['BlurAdmin.theme.components', 'BlurAdmin.theme'])
    .config(function() {
    }).name;

export default module;
```
**modify app.js to import above index.js and my module**
```
...

import BlurAdminTheme from './theme/index'
import MyModule from './pages/pages.module'
...


angular
    .module('BlurAdmin', [
        'ui.router',

```

Let me know if that works. I'm forking the BA repo and creating a starter, but it may take some time..

**Comment by Disorrder** [comment]
@vijaywm ah, that's crazy! For now, I've just added into gulp Babel compiler. Locally Chrome works fine with pure ES6, but in build task use Babel. I don't use imports, but if I need them in future, I will have to rewrite all js files. And all gulpfiles too x_x

**Comment by djpeace** [comment]
@vijaywm Hi, any progress on your project?

**Comment by marcus2vinicius** [comment]
relationship post 
https://github.com/akveo/blur-admin/issues/321
