### ISSUE TITLE
the is no Time control in you system demo.

### ISSUE THREAD

**Issue by godlike110** [akveo/blur-admin#134]
so  how can i use time select control in you system

**Comment by PaiN33708** [comment]
Who are you and I don't know what your talking about


Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by godlike110** [comment]
no datapicker in your blue-admin

**Comment by PaiN33708** [comment]
I didn't comment I don't K of what you talking about

Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by godlike110** [comment]
no datepicker in your blur-admin,a controller using to select time

**Comment by chanakaDe** [comment]
@godlike110  you can use this
https://angular-ui.github.io/bootstrap/#/datepickerPopup

**Comment by nnixaa** [comment]
Hey @PaiN33708 you most likely receiving these messages as you subscribed to our blur-admin repository here on github. To stop receiving these messages please un-watch it.

@godlike110 hopefully you find @chanakaDe's answers useful, let us know if you have any questions.
