### ISSUE TITLE
How to use a third party datepicker in this template ? 

### ISSUE THREAD

**Issue by chanakaDe** [akveo/blur-admin#135]
Hi,
This is a good template and all others in there.
But how can we use a datepicker ?
There's no any documentation too.
I asked earlier too. How can we use third party libraries and how can we add them manually ?
Hey guys, you there? No community support ?
http://xdsoft.net/jqplugins/datetimepicker/
Imagine I want to use this library. How can I do that please ?

**Comment by chanakaDe** [comment]
We can use this one
https://angular-ui.github.io/bootstrap/#/datepickerPopup

**Comment by umbecanessa** [comment]
Hey can you copy a plunk with your implementation ? my eyes are starting to roll
