### ISSUE TITLE
Sidebar issue on mobile devices.

### ISSUE THREAD

**Issue by mayur-mi** [akveo/blur-admin#15]
On mobile devices, sidebar should close automatically on selecting any menu item. Good for UX ?

**Comment by KostyaDanovsky** [comment]
@mayur-mi, thanks for the pull-request. Motly I agree with you, but we need to think about another solution, not just call `menuCollapse` method, maybe add some animation/delay, because now with your fix it looks wierd.

**Comment by lugovsky** [comment]
Closed via 6f6e119
