### ISSUE TITLE
blur Admin mix .net mvc

### ISSUE THREAD

**Issue by jbabaei** [akveo/blur-admin#150]
hi there. i'm developer. and i want use blur-Admin mix with asp.net mvc.
i locate "dev-release" folder in my project.and load all files.
but it doesn't runs correctly in my local machine.

can you help me?

**Comment by GregWhiteDBA** [comment]
i have the same issue

**Comment by wuzhenda** [comment]
i think supporting needs money? it takes so long and still unclosed yet
