### ISSUE TITLE
add baSidebar items from Controller/Factory

### ISSUE THREAD

**Issue by vazh** [akveo/blur-admin#154]
is there any way to add menu & menu item using controller or factory,

since the one provided in docs was using configuration block.

**Comment by vazh** [comment]
never mind, found it.

**Comment by dracorlll** [comment]
How? Can you share the solution?

**Comment by vazh** [comment]
@dracorlll just copy the addStaticItem into the factory,

**Comment by dracorlll** [comment]
@vazh Thanks

**Comment by vazh** [comment]
@dracorlll you're welcome
