### ISSUE TITLE
Remove loader

### ISSUE THREAD

**Issue by peio72** [akveo/blur-admin#155]
How to completely remove the loader ? Thanx.

**Comment by tamilselvan719** [comment]
As for as I know, the loader is just a css animation so you can safely just remove the loader div....

**Comment by peio72** [comment]
Ok thanx.

What about the code for the loading in theme.run.js ?

Could we replace with ng-cloak or angular-loading-bar ?

**Comment by velkumars** [comment]
I tried to copy the loader for another project, its not working. 
I just copied css related to preloader and place the loader div. 
Do i miss something?
