### ISSUE TITLE
Is this theme is available without angular with bootstrap

### ISSUE THREAD

**Issue by dotnetjalps** [akveo/blur-admin#165]
Hello Team, 

First of all awesome theme, Is this theme is available without angular.js. As we want to use it with ASP.NET MVC without angular.js. 

If you have that version it would be great help. Thank you again for all your efforts. 

Regards,
Jalpesh

**Comment by vazh** [comment]
@dotnetjalps its not available without angular.
as someone from akveo stated in issues heere, i forgot the number.
because they need to reconfigure it, so it needs a lot of work.

**Comment by dotnetjalps** [comment]
Okay thanks

**Comment by lugovsky** [comment]
https://github.com/akveo/blur-admin/issues/4
