### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by sayedjafar** [akveo/blur-admin#172]
It is an amazing project with organized code. It will be great to have right to left support?

**Comment by MetaiR** [comment]
about 2 month ago , I started project of making this beautiful panel RTL.
It is a challenge because it's too complex and hard to understand.
until now the navigation's, card's, and some of it's component get's RTL

**Comment by lugovsky** [comment]
@sayedjafar Sorry, but for now we don't expect to support RTL :(
@MetaiR Let us know if you will have any success making it RTL. We would gladly refer to your project in this case

**Comment by MetaiR** [comment]
@lugovsky 
yes we working on it.
all navigation and headers and footer now rtl.
but it's hard because we don't know your architecture
does this repository have any Gitter channel?

**Comment by alimusavi67** [comment]
@MetaiR any luck?

**Comment by phpirate** [comment]
@MetaiR  Did you guys get any progress on this?
