### ISSUE TITLE
how to integrate Blur Admin with PHP using Gulp+AMP

### ISSUE THREAD

**Issue by drake0101** [akveo/blur-admin#175]
Hello,
Recently I have been working on some layout changes in Blur Admin. So far I used recommended method of: git pull + gulp serve, and I just edit the files. 
Now I would like to (for example) rename Blur Admins index.html to index.php and add some PHP code there. Is it possible to still be able to edit SCSS files, is it possible for gulp to (for example) still inject proper <script> tags to index.PHP? is it possible to have all this but with support for PHP?
I do have my own Apache+PHP+MySQL installation on localhost and I would like to use it, as it is exact replica of my production server.
Any help would be very appreciated.

**Comment by lugovsky** [comment]
@drake0101 It's completely possible, though would require changes in terms of build and configuration based on your needs. I'm not sure if we would be able to provide any exact help in scope of this issue because it really depends.
