### ISSUE TITLE
Smart Table pagination

### ISSUE THREAD

**Issue by udaybchaudhari** [akveo/blur-admin#177]
I would like to control the pagination in smart table. That mean I want to send only 50 records from the server and when user clicks on next page it will bring next 50 records. 
In short, I want to send total records count variable and set the pages according to it. When user clicks on specific page get the data from database only for that page.
How can I do that in smart table?

**Comment by ESadouski** [comment]
@udaybchaudhari Please look at documentation of Smart Table (https://lorenzofox3.github.io/smart-table-website/). Also I think this example can help you http://plnkr.co/edit/wzUHcc9PBF6tzH8iAEsn
