### ISSUE TITLE
Change load background

### ISSUE THREAD

**Issue by khanhbvh** [akveo/blur-admin#179]
Hi all, how can i change black color to another color when begin load 
![image](https://cloud.githubusercontent.com/assets/10255250/19016435/ebdaae0e-8843-11e6-9d8f-dc869be49daf.png)

**Comment by tamilselvan719** [comment]
in main.css search for #preloader selector you can change it there,
or if you are using sass files you search the same in main.sass too...

**Comment by khanhbvh** [comment]
That work for me, thank u!
