### ISSUE TITLE
bootstrap-select with angular

### ISSUE THREAD

**Issue by tanahara** [akveo/blur-admin#18]
The select picker directive does not work with ng-options or just a simple ng-repeat consistently. On rare rare occasion the drop down will render. My guess is the below is the issue.

`        setTimeout(function() {
          elem.selectpicker({dropupAuto: false});
        }, 0);`

**Comment by lugovsky** [comment]
Yeah, I think you're right. Feel free to provide PR if you want this issue to be fixed quickly. In any case we will fix it ourselves after we finish major features currently in development

**Comment by tanahara** [comment]
Understood, thank you for the response.

**Comment by lugovsky** [comment]
@tanahara Fixed it in master, but unfortunately only made it possible using ngOptions. For now I think it should be enough. In future, I think we change bootstrap-selectpicker to some other library, because it's hard to integrate it with Angular.
