### ISSUE TITLE
how to edit it easyly

### ISSUE THREAD

**Issue by MetaiR** [akveo/blur-admin#181]
hello,
as said in title, how to do this?
because the files are compressed and supper hard to understand

**Comment by zygmcc** [comment]
same problem, it is too complex...

**Comment by josephbisaillon** [comment]
None of the files are compressed until your build for deployments. The files provided are uncompressed and easy to understand if you know angular.

**Comment by PhiLhoSoft** [comment]
Don't use "View source" on the demo, follow the installation instructions... 😄

**Comment by lugovsky** [comment]
Yup, just follow installation instruction guys :)
