### ISSUE TITLE
bluar admin localStorage expiration

### ISSUE THREAD

**Issue by brijesh1ec** [akveo/blur-admin#182]
Hi,

I have tried integrating localStorage, but how i can set Expirtation time (example 20 minute) if user is inactive so it will logout.

**Comment by vlaad360** [comment]
http://hackedbychinese.github.io/ng-idle/
You can look here

**Comment by lugovsky** [comment]
Localstorage does not have any timeout for it's data. It would be always more secure to implement server-side toke expiration. Unfortunately this question is not blurAdmin related.
