### ISSUE TITLE
show preloader when call api from server

### ISSUE THREAD

**Issue by khanhbvh** [akveo/blur-admin#185]
Hi all! 
I have APIs from server, and i want when client call an api then show preloader and hide when api response result.
How can i do that, please help!

**Comment by dboscanv** [comment]
Hi!

You can use _Angular Loading Bar_, _PACE_ or _blockUI_ with an interceptor, it's easy.

**Comment by ESadouski** [comment]
@khanhbvh Note how we work with Promises in the 'theme.run.js'. For example, you can add a new promise to the 'whatToWait' array and resolve this Promise when your request is complete.
