### ISSUE TITLE
How to add a new assets folder

### ISSUE THREAD

**Issue by jmejiaz** [akveo/blur-admin#186]
Hi , this is the question.

I've created a new sub folder folder inside the assets folder , and every goes well using `gulp serve`  , but when I use `gulp serve:dist` the new folder dissapears. 

How can I do this?  Thanks in advance

**Comment by josephbisaillon** [comment]
`gulp serve:dist` runs gulp build which will blow out your newly created folder. Under `gulp/server.js` you will see `gulp.task('serve:dist', ['build'], function () {` try changing it to `gulp.task('serve:dist', function () {` and see if that works.

**Comment by lugovsky** [comment]
@jmejiaz `assets` folder is intended to contain images, video files and other files of this type. Everything that has extensition {html,css,js,scss,md} is being not included in resulting build. These files should be in their appropriate directories.

Please take a look at this line:
https://github.com/akveo/blur-admin/blob/master/gulp/build.js#L87
