### ISSUE TITLE
Cache problem on client side

### ISSUE THREAD

**Issue by jaydeepva** [akveo/blur-admin#191]
Hi,

We are using bluradmin theme for management app. We have noticed that after every deployment, the updated functionality is not available to user, unless the cache is cleared.

Sometimes it takes more than 1 attempts to clear the cache till the functionality works. Any suggestions or  recommendations to get over this issue?

Thanks.

**Comment by josephbisaillon** [comment]
Are you deploying the minified build? Because mine appends what appears to be a hash of some sort to the end of the minified files so that it forces browsers to do a cache refresh.

**Comment by vazh** [comment]
@jaydeepva 
some browsers do that,
is it works that way for all browsers ?
because a colleague of mine use firefox while i use chrome, i didn't encounter this problem, but she did.
she needs to hard refresh the browser to load the new one(ctrl+f5 in case you didn't know).

**Comment by lugovsky** [comment]
@jaydeepva each time you deploy your app, assets receive new cachebust parameter in URL which usually equals to git hash. If your don't see your app seem to be updated, that means that most possibly your CDN/Web server etc. don't rotate cache. In this case, it's not related to BlurAdmin rather to your environment configuration
