### ISSUE TITLE
How to remove the entrance transition of all the UI elements

### ISSUE THREAD

**Issue by demichalk** [akveo/blur-admin#193]
Is it possible to disable easily the expansion UI effect that every UI element when it enters the content area on the right?  Is this an easily configurable animation effect?

**Comment by ESadouski** [comment]
@demichalk Yes, it's possible. If you want to disable the expansion UI elements you can delete class zoomIn from BaPanel elements (look at zoomIn directive). And if you want to configurate animation please look at _panel.scss
