### ISSUE TITLE
How to Implement a notificaction with a button for a modal message

### ISSUE THREAD

**Issue by senneko** [akveo/blur-admin#195]
Hi!!!

I tried to implement a notification with a button inside, for a modal message.

unfortunately, it doesnt work.

Here is how I tried to do:

`$scope.options.type = 'success';
$scope.options.msg = 'Operacion ' + response.data[i].operacion + ' Exitosa <br><br> <button type="button" class="btn btn-primary" data-toggle="modal" ng-click="open(\'app/pages/ui/modals/modalTemplates/successModal.html\', \'md\')">Clic para más información</button>';
$scope.descripcion = response.data[i].descripcion;
$scope.openToast();`

This is the open function:

`$scope.open = function (page, size) {
      $uibModal.open({
        animation: false,
        templateUrl: page,
        size: size,
        resolve: {
          items: function () {
            return $scope.items;
          }
        }
      });
    };`

![image](https://cloud.githubusercontent.com/assets/6578465/19832672/cfe8c552-9def-11e6-8b67-2b021a49735f.png)

When I click the button, the modal message doesnt work, and there is no error.

Here is the controller header:

`function AppCtrl($scope, $timeout, $http, $uibModal, toastr, toastrConfig) {`

I hope you can help me.

**Comment by vlaad360** [comment]
Look here
https://codepen.io/long2know/pen/ZGgJwv

**Comment by senneko** [comment]
Thanks a lot!!! @vlaad360
