### ISSUE TITLE
is there any way to run this template on another server rather than node

### ISSUE THREAD

**Issue by cerokool32** [akveo/blur-admin#20]
I like this template but my development is focused on apache servers (apache2, tomcat and tomee), is there any way to use it on this servers?

**Comment by lugovsky** [comment]
This template is just HTML template, so it doesn't matter if you serve it with apache, nginx or any other web server. Though you would need to have appropriate Apache configuration and modify gulp build

**Comment by iyer24** [comment]
I'd like to know how do you modify gulp build in order to achieve this

**Comment by alpamys-qanybet** [comment]
@iyer24 ``dist`` stands for ``distribution`` so I just use ``guls serve:dist`` and take the generated ``release`` folder for my php project.
