### ISSUE TITLE
bower install can not input

### ISSUE THREAD

**Issue by JsonRoob** [akveo/blur-admin#200]
Unable to find a suitable version for jquery, please choose one by typing one of the numbers below:
    1) jquery#~2.1.4 which resolved to 2.1.4 and is required by blur-admin
    2) jquery#~2.1.1 which resolved to 2.1.4 and is required by bootstrap-tagsinput#0.5.0
    3) jquery#>=1.8 which resolved to 3.1.1 and is required by bootstrap-select#1.9.4, ionrangeslider#2.1.4
    4) jquery#>=1.9.0 which resolved to 3.1.1 and is required by bootstrap-switch#3.3.2, jquery.easy-pie-chart#2.1.6
    5) jquery#>=1.6 which resolved to 3.1.1 and is required by jquery-ui#1.12.1, jquery-ui#1.11.4
    6) jquery#>=2.0.0 which resolved to 3.1.1 and is required by fullcalendar#2.4.0
    7) jquery#>=1.9.1 which resolved to 3.1.1 and is required by jstree#3.3.3
    8) jquery#>= 2.1.0 which resolved to 3.1.1 and is required by morris.js#0.5.1
    9) jquery#>=3.1.x which resolved to 3.1.1 and is required by angular-ui-sortable#0.13.4
    10) jquery#>= 1.2.1 which resolved to 3.1.1 and is required by jquery.easing#1.3.1
    11) jquery#1.9.1 - 3 which resolved to 3.1.1 and is required by bootstrap#3.3.7
    12) jquery#>=1.7 which resolved to 3.1.1 and is required by angular-slimscroll#1.1.5

Prefix the choice with ! to persist it to bower.json

**Comment by vazh** [comment]
just select number1

**Comment by lugovsky** [comment]
Thanks @vazh
