### ISSUE TITLE
how to inject css/js to a new html file

### ISSUE THREAD

**Issue by blackmatch** [akveo/blur-admin#206]
Hello, everyone! I create a new html file called 'pwd.html' on the same folder of auth.html. And I also copy all the code from auth.html. And then I add 'pwd.html' to gulp/inject.js. like below:
`gulp.task('injectAuth', ['stylesAuth'], function () {
  return injectAlone({
    css: [path.join('!' + conf.paths.tmp, '/serve/app/vendor.css'), path.join(conf.paths.tmp, '/serve/app/auth.css')],
    paths: [path.join(conf.paths.src, '/auth.html'), path.join(conf.paths.src, '/reg.html'), path.join(conf.paths.src, '/pwd.html')]
  })
});`
and then I run 'gulp inject', and then 'gulp build'. But the 'pwd.html' did not contains the 'stylesAuth', it was said that the style on the auth.html did not copy to pwd.html. Anyone can tell me the right way to inject css/js to a new html file?

**Comment by OssprO** [comment]
Remember to include these lines in your pwd.html file:

```
  <!-- build:css({.tmp/serve,src}) styles/vendor.css -->
  <!-- bower:css -->
  <!-- run `gulp inject` to automatically populate bower styles dependencies -->
  <!-- endbower -->
  <!-- endbuild -->

  <!-- build:css({.tmp/serve,src}) styles/auth.css -->
  <!-- inject:css -->
  <!-- css files will be automatically insert here -->
  <!-- endinject -->
  <!-- endbuild -->
```
Inside the `<head>` tag
