### ISSUE TITLE
gulp serve throws error-- [Sass] Error in plugin 'gulp-sass'

### ISSUE THREAD

**Issue by guayeguaye** [akveo/blur-admin#235]
> node version v7.4.0
> npm version 4.0.5

how to resolve??

[11:17:49] gulp-inject 56 files into main.scss.
[11:17:49] [Sass] Error in plugin 'gulp-sass'
Message:
    src\sass\theme\dashboard\_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.
Details:
    status: 1
    file: D:/blur-admin-1.1.1/src/sass/theme/dashboard/_timeline.scss
    line: 196
    column: 3
    formatted: Error: Mixins may not be defined within control directives or other mixins.
        on line 196 of src/sass/theme/dashboard/_timeline.scss
  @mixin cd-timeline-left-color($color) {
    messageFormatted: src\sass\theme\dashboard\_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.
[11:17:49] Finished 'styles' after 2.42 s

**Comment by guayeguaye** [comment]
As a quick workaround I just moved the cd-timeline-left-color mixin which is in the src/sass/theme/dashboard/_timeline.scss file on the line 196 out of the parent media condition @media only screen and (min-width: $resXL) {, so put it right before the line 156 and ran gulp serve again.
Worked for me.

`you can look the link`
[https://github.com/akveo/blur-admin/issues/21](url)

**Comment by vinayagam05** [comment]
https://github.com/akveo/blur-admin/issues/21
 404 Error
