### ISSUE TITLE
How to use a angular admin theme

### ISSUE THREAD

**Issue by kajann** [akveo/blur-admin#24]
This is a question. I'm not sure how to use this theme with my application. 

Basically I have a page with a landing page and I'm trying to use a dashboard theme. So if a user logs in they will be redirected to the dashboard. Would I install your theme as a bower install and use it or how would it work.

I've never used existing admin themes before, that is why I have this question.

Thanks,

**Comment by lugovsky** [comment]
Hi Kajann, in your place I would kept landing page and dashboard page separately and figure out routing questions using some webserver like nginx or apache. In this case you can clone our repo, remove everything you don't need and develop your features inside of your copy.

For example if you have your landing page at **mywebsite.com**. You can have dashboard at **mywebsite.com/app/**. In your webserver config you would just need to set different document root for everything that starts from **/app**

**Comment by kajann** [comment]
Ahh, that would be great idea. Thanks for that. 

Is there any tutorial out there about how to customize a theme.

**Comment by lugovsky** [comment]
Actually here's wiki page abou costomizing "blur" theme: https://github.com/akveo/blur-admin/wiki/How-to-change-color-scheme

As well, you could check out **mint** where we trying to create some light colorscheme without blur effect
