### ISSUE TITLE
Gulp build error - Unknown provider: baSidebarServiceProvider

### ISSUE THREAD

**Issue by anushTv** [akveo/blur-admin#247]
My project built using BlurAdmin works fine when running in dev mode (gulp serve)
However when building the project using command 'gulp build', I'm seeing following errors and unable to build the code. Has anyone seen this error?
The baSidebarService & related provider code were as-is and not modified.

generated.js:42846Uncaught Error: [$injector:modulerr] Failed to instantiate module BlurAdmin due to:
Error: [$injector:modulerr] Failed to instantiate module BlurAdmin.pages due to:
Error: [$injector:unpr] Unknown provider: baSidebarServiceProvider
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=baSidebarServiceProvider
    at http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:377
    at http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:21706
    at i (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:20657)
    at r (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:20962)
    at Object.a [as invoke] (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:21134)
    at i (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:20044)
    at http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:20168
    at i (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:828)
    at d (http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:19945)
    at http://localhost:5000/scripts/vendor-c7c4c705b0.js:282:20114

**Comment by 841660202** [comment]
how to solve?

**Comment by MetalMor** [comment]
Hi,

I recently solved this issue. Injections are wrong after minification (which is a process ran on 'build' gulp task). You have to remove any `/* @ngInject */` annotation from all sources and then add the dependencies needed in each module to the dependency injection array. It may look like this:

```
angular.module('BlurAdmin.theme')
      .service('baPanelBlur', ['baPanelBlurHelper', '$window', '$rootScope', baPanelBlur]);

  function baPanelBlur(baPanelBlurHelper, $window, $rootScope) {
    // some stuff here...
  }
}
```

You might find useful information in the [dependency injection article](https://docs.angularjs.org/guide/di) in the developer guide.

Happy coding :)

**Comment by xiaoyusis** [comment]
Have you solved it?
