### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by brightliming** [akveo/blur-admin#248]
I got many errors when I run the npm install.  Below is the error log:

Bus error (core dumped)
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bright/project/idea-project/blur-admin/npm-debug.log

**Comment by fkheddar** [comment]
i got the same error :(

**Comment by fidge** [comment]
same error over here

**Comment by dimplejaiswal** [comment]
Remove node-sass": "^3.13.1" from package.json. These errors will get vanished.

**Comment by DreamoverStudio** [comment]
I got the same error

**Comment by Cu4rach4** [comment]
im using node 4.2.1 and npm 3.3.8, try to us nvm to install and management your version then use npm install -g npm@3.3.8

then on blur - admin folder: 

npm install -g bower
npm install
npm install -g gulp

bye

**Comment by DreamoverStudio** [comment]
@Cu4rach4 Problem solved, thanks

**Comment by Cu4rach4** [comment]
you welcome...close @brightliming issue please!

**Comment by brightliming** [comment]
@Cu4rach4 thanks for your help
