### ISSUE TITLE
Creating a page that should NOT be displayed at the sidemenu

### ISSUE THREAD

**Issue by FishTheOriginal** [akveo/blur-admin#257]
Hi there,

I'm making an edit page that should be accessible through a URL but it should not be displayed in the menu, it requires ID param to know which item to edit that is in link in a list page.

Is there a flag I could set to make the item NOT append automatically to the menu?
```
		.state('item.edit', {
			url: '/edit/:id',
			templateUrl: 'app/pages/item/edit/itemEdit.html',
			title: 'Item Edit',
			controller: 'ItemEditCtrl',
			sidebarMeta: {
				order: 0,
			},
		})
```

Best regards,
Sergey

**Comment by turakvlad** [comment]
@FishTheOriginal, hi!

To my mind, you should just remove `sidebarMeta` object. Hope it will help.

**Comment by FishTheOriginal** [comment]
Right to the point. Thanks worked perfectly!
