### ISSUE TITLE
Is it possible to change the skin of the theme?

### ISSUE THREAD

**Issue by felixgondwe** [akveo/blur-admin#26]
Am trying to change theme skin colors, I am a newbie at angular so bear with me for a second. Is there a way to change skin of the BlurAdmin dynamically?

**Comment by lugovsky** [comment]
Hi @felixgondwe

What do you mean by "dynamically"? Without page reload or with page reload?

**Comment by felixgondwe** [comment]
Hi @lugovsky,

With page reload. Thanks.

**Comment by lugovsky** [comment]
We have created page on wiki describing color customization process: https://github.com/akveo/blur-admin/wiki/How-to-change-color-scheme

But in general, you would need to general several css files and have several `theme.constants.js` JS files with appropriate skin colors

**Comment by felixgondwe** [comment]
Sweet! thank you so much.
