### ISSUE TITLE
Calendar not displaying everything

### ISSUE THREAD

**Issue by ErikLillehagen** [akveo/blur-admin#261]
in your dashboard you use fullcalendar, and if you look at the code define your header as:
header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },

today,  'month, agendaWeek, agendaDay'
should be buttons, but they are never displayed.

**Comment by IssamEssarghini033** [comment]
Go to : blur-admin/src/sass/theme/dashboard/_calendar.scss
and you'll find : 
`.fc-today-button, .fc-month-button, .fc-agendaWeek-button, .fc-agendaDay-button  {
  display: none;
}`

**Comment by maurogs11** [comment]
It works ^^
