### ISSUE TITLE
side menu animation on click.

### ISSUE THREAD

**Issue by painhardcore** [akveo/blur-admin#27]
Having some issue with left menu when it's minimized, on-click that panel don't roll to right side.
on demo http://akveo.com/blur-admin/#/dashboard it working ok. but when i use git's verion - it's not working sub-menu are expanding, but the main left menu don't roll.
In install process only that error came up, of course i use 1.4.0....

> Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
>     1) angular#1.3.x which resolved to 1.3.20 and is required by angular-morris-chart#1.1.0
>     2) angular#1.4.10 which resolved to 1.4.10 and is required by angular-animate#1.4.10, angular-route#1.4.10, angular-touch#1.4.10
>     3) angular#>=1.3.0 which resolved to 1.4.10 and is required by angular-bootstrap#0.14.3, angular-toastr#1.7.0
>     4) angular#~1.x which resolved to 1.4.10 and is required by angular-progress-button-styles#0.1.0, angular-xeditable#0.1.12
>     5) angular#^1.0.0 which resolved to 1.4.10 and is required by angular-smart-table#2.1.8
>     6) angular#>=1.2.x which resolved to 1.4.10 and is required by angular-ui-sortable#0.13.4
>     7) angular#^1.0.8 which resolved to 1.4.10 and is required by angular-ui-router#0.2.18
>     8) angular#~1.4.8 which resolved to 1.4.10 and is required by blur-admin
>     9) angular#^1.2.28 which resolved to 1.4.10 and is required by angular-chartist.js#3.3.13
>     10) angular#1.4.x which resolved to 1.4.10 and is required by angular-chart.js#0.8.9
>     11) angular#~1.4 which resolved to 1.4.10 and is required by ng-js-tree#0.0.8
>     12) angular#>=1.3.x which resolved to 1.4.10 and is required by textAngular#1.4.6

I've matched <a> tag from my local copy and demo site
demo
`<a ng-mouseenter="hoverItem($event, item)" ng-if="item.subMenu" href="" ng-click="toggleSubMenu($event, item)" class="al-sidebar-list-link ng-scope ng-click-active"><i class="ion-stats-bars"></i><span class="ng-binding">Charts</span> <!-- ngIf: item.subMenu --><b class="fa ng-scope fa-angle-down" ng-class="{'fa-angle-up': item.expanded, 'fa-angle-down': !item.expanded}" ng-if="item.subMenu"></b><!-- end ngIf: item.subMenu --></a>`

localhost
`<a ng-mouseenter="hoverItem($event, item)" ng-if="::item.subMenu" class="al-sidebar-list-link ng-scope" ba-ui-sref-toggler="item.stateRef"><i class="ion-stats-bars"></i><span class="ng-binding">Charts</span> <!-- ngIf: ::item.subMenu --><b class="fa fa-angle-down ng-scope" ui-sref-active="fa-angle-up" ng-if="::item.subMenu"></b><!-- end ngIf: ::item.subMenu --></a>`

What wrong?

> { npm: '2.15.1',
>   ares: '1.10.1-DEV',
>   http_parser: '2.5.2',
>   icu: '56.1',
>   modules: '46',
>   node: '4.4.4',
>   openssl: '1.0.2h',
>   uv: '1.8.0',
>   v8: '4.5.103.35',
>   zlib: '1.2.8' }

**Comment by lugovsky** [comment]
@painhardcore Yup seems like it's a bug of current snapshot. Thanks for reporting!
