### ISSUE TITLE
Problem with gulp command.

### ISSUE THREAD

**Issue by MEKDAD3** [akveo/blur-admin#29]
hi i have a problem with gulp command , would someone please compile the template and send me the realase folder . thanks

**Comment by Sopheakmorm** [comment]
I have the same problem

**Comment by MEKDAD3** [comment]
this is what i get when i run the command npm install :
bower                                         ECONFLICT Unable to find suitable version for angular.

**Comment by Sopheakmorm** [comment]
Do you have any solutions for this problems ?

**Comment by MEKDAD3** [comment]
no , i've tried all the angular js versions but nothing worked.

**Comment by Sopheakmorm** [comment]
Did you check with Node js version ?

**Comment by MEKDAD3** [comment]
yes i have update it

**Comment by Sopheakmorm** [comment]
I got this error when I try to build this project

**Comment by MEKDAD3** [comment]
Can somebody upload the release ?

**Comment by Sopheakmorm** [comment]
hashas.....this is what I need :+1:

**Comment by Sopheakmorm** [comment]
I will try to release it again to night. If success I will send to you

**Comment by MEKDAD3** [comment]
Yeah ... that would be great (y)

**Comment by Sopheakmorm** [comment]
now I built it completed . give me your email . I will send you

**Comment by MEKDAD3** [comment]
here is my email mekdad3@gmail.com . thank you very much !!

**Comment by Sopheakmorm** [comment]
got it ?

**Comment by MEKDAD3** [comment]
yeaah you saved my day thank you ;) :+1:

**Comment by Sopheakmorm** [comment]
goooooooooood job sir !!!!

**Comment by Sopheakmorm** [comment]
May I ask you one question ?
I would like to integrate this template with ASP MVC. could you help me ?

**Comment by MEKDAD3** [comment]
i would be happy to help you but im just a beginner , and im more familiar with php framworks. sorryyy siir.

**Comment by Sopheakmorm** [comment]
ok thank you

**Comment by AllyW** [comment]
can I have a copy of the release one too? I have build problem in my environment either. My email anrannj@gmail.com.

**Comment by javahuat** [comment]
Can email me too if possible. My email is javahuat@hotmail.com

**Comment by lugovsky** [comment]
Hi guys,

You can find non-compressed development files here as well now: http://akveo.github.io/blur-admin/articles/091-downloads/

**Comment by Sopheakmorm** [comment]
Hey guys,
Please check your email. I've sent to you already

**Comment by AllyW** [comment]
Hi Sopheakmorm, I got your email with release sharing folder. Thanks.

For other developers, I found it cannot be built in windows system but works perfectly on my mac. So, use *nux to save your life for building, or just use the release folder under windows.
