### ISSUE TITLE
Only Block the page instead of whole portal

### ISSUE THREAD

**Issue by skyline9002** [akveo/blur-admin#296]
Hi ，

I want to block the pages (except the top and sidebar) instead of the whole portal. How can I do that?

Thanks

Simon

**Comment by melvinodsa** [comment]
Comment out the unnecessary pages from the pages.module.js. Also delete the those page folders if not intended to use them in future.

**Comment by skyline9002** [comment]
Sorry, I mean the black loading page when get into the portal, it will cover the hole portal. Actually I want to use that if my page loading ajax request. I dont want to cover the whole portal I only want to cover the page and leave topbar and sidebar available.
