### ISSUE TITLE
Why 'echarts' can't be auto injected? 

### ISSUE THREAD

**Issue by liuhao2050** [akveo/blur-admin#298]
Hello, I just  install echarts by bower and it doesn't  injected to index.html, but some else lib is normal.

**Comment by liuhao2050** [comment]
The Echarts doesn't create bower.json

**Comment by wangzl4neusoft** [comment]
I have defined echart.js in bower.json file. But it is not still injected automatically.
code as following:
  "dependencies": {
    "echarts": "~3.4",

**Comment by wangzl4neusoft** [comment]
In blur admin version 1.3.1, we should declare echarts in bower.json
it includes:
1: input echart in dependencies:
e.g.
"dependencies": {
"echarts": "~3.4",
2: declare load items in overrides:
e.g.
    "echarts":{
      "main":[
        "./dist/echarts.js",
        "./dist/extension/bmap.js",
        "./dist/extension/dataTools.js"
      ]
    },
Best Regards

**Comment by Mary526** [comment]
Yes, it helped me a lot.
![image](https://user-images.githubusercontent.com/15365812/37012862-c7c54ad2-2131-11e8-974f-c0e2b4fa258d.png)
but what confused me , why `gulp injet` didn't work ?
Anyway , it's the right answer
