### ISSUE TITLE
Support for ES6 code

### ISSUE THREAD

**Issue by shankarregmi** [akveo/blur-admin#321]
is there any way, I can run babel transpiler before the uglify code runs for `app/**/*.js` ?
I have added babel in build scripts 
```
gulp.task('scripts', function() {
  return buildScripts();
});

function buildScripts() {
  return gulp.src(path.join(conf.paths.src, '/app/**/*.js'))
    .pipe($.babel({presets: ['es2015']}))
    .pipe($.eslint())
    .pipe($.eslint.format())
    .pipe($.size())
};
```

However , I get `Unexpected token '=>' while running `gulp serve:dist`

**Comment by marcus2vinicius** [comment]
Following...

**Comment by TommyZJL** [comment]
Trying this also.

**Comment by lijifeng** [comment]
I tried many ways to use babel, but angularJs could not be loaded properly. Then I finally found that the reason why es6 could not be used was the execution of eslint and uglify, so I deleted the dependency of Babel, updated eslint, replaced uglify with gulp-uglify-es, and then es6 syntax could be used in the controller.
Here are my modifications:

1.  gulp-uglify can be removed or replaced with gulp-uglify-es，then as the document says，modify the build. js
```
  let uglify = require('gulp-uglify-es').default; 
  .pipe(uglify())
```
2. eslint upgrade
```
  "eslint": "^5.12.0",
  "gulp-eslint": "^5.0.0",
  "eslint-plugin-angular": "^4.0.0",

and  .eslintrc, just copied from somewhere
{
  "env": {
    "browser": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "globals": {
    "angular": true
  },
  "rules": {
  }
}       
```

**Comment by TommyZJL** [comment]
@lijifeng did you get es6 transplied to es5 properly after `gulp build` process?

**Comment by lijifeng** [comment]
@TommyZJL I may not understand what you mean, gulp build or gulp default is normal after using the es6 syntax. I tried to use 'let' or 'pormise' in es6 grammar, which are also intact in the compressed js，but not es5.

**Comment by TommyZJL** [comment]
@lijifeng I get your point, but what I am saying is that we need to transplie our es6 source code (`let`, `const` or array function syntax) into es5 before we put into dist folder and then we can provide cross-browser compatibility. otherwise, `let` and `const` syntax is only supported in Chrome and some other modern browsers and would not be executable on browser like IE 11.

**Comment by lijifeng** [comment]
@TommyZJL Well, babel is probably the only way to do this, in the process of trying babel, using babel8.0 can make it compatible with gulp, but I haven't found a way to make it compatible with angularjs, sorry I can't help you.

**Comment by TommyZJL** [comment]
@lijifeng I am trying to use babel 8.0 and add gulp-babel in the gulp tasks but seems not working. I will create a PR once I make it.
