### ISSUE TITLE
Build Source

### ISSUE THREAD

**Issue by guangmang** [akveo/blur-admin#33]
When I run npm install , then get the follow error, my development environment is windows 10 and visual studio 2015.  what wrong? 

![image](https://cloud.githubusercontent.com/assets/17451949/15327694/ebf714d4-1c84-11e6-8625-383d269e8bd3.png)

**Comment by lugovsky** [comment]
@guangmang Can't really understand error message.

But there's a chance you might be experiencing this issue: https://github.com/sass/node-sass/issues/1387#issuecomment-185451183

**Comment by Chowarmaan** [comment]
I add the --msvs-version=2015 (or 2012, etc...) to my npm commands (npm install --msvs-version=2015 ...) to help with the installation on Windows. As @lugovsky indicated, ensure you have the right versions of node, npm, etc...  I do not see an error in your screen shot though, as the ones listed seem to be testing settings then correcting the install.

**Comment by lugovsky** [comment]
As well, if you still experience this issue you can download development (non-compressed) and production (compressed) files here http://akveo.github.io/blur-admin/articles/091-downloads/
