### ISSUE TITLE
backTop and slimScroll is not a function

### ISSUE THREAD

**Issue by Sopheakmorm** [akveo/blur-admin#34]
Hi all,
I have tried to integrate blurAdmin with ASP.Net and I met big one problem with javascript
```
vendor-3eb5f18f5d.js:28226 TypeError: $(...).backTop is not a function
vendor-3eb5f18f5d.js:28226 TypeError: $(...).slimScroll is not a function
```
Could you help me ?
Thanks you guy!!!!!!!!!

**Comment by KostyaDanovsky** [comment]
@Sopheakmorm, can you provide more details?
How did you build your sources?
And what scripts did you add on the page?

**Comment by Sopheakmorm** [comment]
Thank,
I built with script gulp and I get fresh html then I copy script and style sheet to asp project after that I have tried to build it and run but I got some that above errors in consolve browser

**Comment by nnixaa** [comment]
@Sopheakmorm most likely paths to scripts/css files are not correctly specified in your template (html) file. Try adding a leading / into the path so that your src attributes will look like this:
`src="/filename.js"`. Hope this helps.

**Comment by lugovsky** [comment]
Look like this issue is not related to framework itself
