### ISSUE TITLE
how to use blur-admin without gulp

### ISSUE THREAD

**Issue by sanwal123** [akveo/blur-admin#345]
I am using blur admin with node js.
I copied all the files from src file to my public/admin folder and set paths in my node server as when ever I hit http://localhost:3002/admin it takes me to index page of blur admin. Everything is working fine.

The problem comes when I add a new page in app/pages
e.g
folder: pager which has a empty html and a pager.module.js file

code for pager.module.js
(function () {
  'use strict';

  angular.module('BlurAdmin.pages.pager', [])
      .config(routeConfig);

  /** @ngInject */
  function routeConfig($stateProvider) {
    $stateProvider
        .state('pager', {
          url: '/pager',
          templateUrl: 'app/pages/pager/mypager.html',
          title: 'My New Pager',
          sidebarMeta: {
            order: 800,
          },
        });
  }

})();
I have also included 'BlurAdmin.pages.pager' in pages.module.js.

When I restart the node server the blur admin gives me following error and the page gets stuck on loading animation

Uncaught Error: [$injector:modulerr] Failed to instantiate module BlurAdmin due to:
Error: [$injector:modulerr] Failed to instantiate module BlurAdmin.pages due to:
Error: [$injector:modulerr] Failed to instantiate module BlurAdmin.pages.pager due to:
Error: [$injector:nomod] Module 'BlurAdmin.pages.pager' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

So I downloaded a new copy of blur admin and added a new page as described above but this time I ran gulp and new page came up working without any problem.

What am I missing ? by running gulp blur-admin accepts any number of new pages but when we simply call pages via node server it simply rejects any new page that didn't come with downloaded project.

Please help I would really like to learn and work in this template.

**Comment by tassiopimentel** [comment]
@sanwal123 I'm having the same problem as you, did you solve it?

When I create the page the same way it explains on this page http://akveo.github.io/blur-admin/articles/013-create-new-page/

The error still continues ...

**Comment by sanwal123** [comment]
lemme get back to you. Yes I did solve it. It was really simple.

**Comment by Bankai2212** [comment]
Same problem here... Can you explain how to solve this issue? Thanks in advance.

**Comment by sanwal123** [comment]
Hey manpreet,
when you create a new file/page, the gulp creates reference to that file
automatically in the index.html page.

So now in the absence of gulp you have to do it manually.

for example if you create a page as cookie.js then you have to include this
page in the index.html file as

<script src="yourpath/cookie.js"></script>

yourpath is the directory where your cookie.js file is.

Happy coding.

**Comment by SonamKul9527** [comment]
I followed all the steps from http://akveo.github.io/blur-admin/articles/013-create-new-page/ and also the additional steps of adding the myNewPage to page.module.js and in the index.html but still, neither the template is working nor the loading animation is coming up. Kindly, help me in this.
