### ISSUE TITLE
How can I include this front-end template in a JavaEE Web Application?

### ISSUE THREAD

**Issue by crisstelista** [akveo/blur-admin#358]
I want to start a new JavaEE Web application, working with JSPs and Beans. 
How can I include this template inside of my web app?  
I started a new project, developing it in NetBeans.

I am a new developer, I know nothing about front-end side. I would be grateful if you explain me step by step!!!!!!

Many Thanks!!!

**Comment by sabousha** [comment]
You can find many step-by-step instructions online.  You would need to do several things to get the dependencies installed, the source files merged into your codebase and possibly small refactoring to get things to work.

Some advice: Just drop it in and take the few hours or days to try to get it working.  It will be painful at first but it is an excellent learning experience.

Good luck
