### ISSUE TITLE
got error without any changes

### ISSUE THREAD

**Issue by RoraxHan** [akveo/blur-admin#359]
I have cloned this template and executed "npm install" and then I have executed "gulp serve".
gulp is executed successfully but I'v got the error like below in browser console.

`Uncaught Error: [$injector:modulerr] Failed to instantiate module BlurAdmin due to:
Error: [$injector:modulerr] Failed to instantiate module smart-table due to:
Error: [$injector:nomod] Module 'smart-table' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=smart-table
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:2133:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:2057:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:2131:14)
    at http://localhost:3000/bower_components/angular/angular.js:4669:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at http://localhost:3000/bower_components/angular/angular.js:4670:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=smart-table&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'smart-table'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dsmart-table%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A2057%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A2131%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4669%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4653%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4670%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4653%3A5)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4692:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at http://localhost:3000/bower_components/angular/angular.js:4670:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4575:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1809:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1830:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=BlurAdmin&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20smart-table%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'smart-table'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dsmart-`

When I remove the 'smart-table' injection in the app.js then I can run successfully but smart-table is not working.
(I have checked bower_components directory whether angular-smart-table exists on there.)
I don't know what is the reason. Please guide me about this.

**Comment by daibangcanhcut** [comment]
This is because smart-table.js is not injected. To fix this, add the following block of code to bower.json file, next to "font-awesome" block

```
,
    "angular-smart-table" : {
      "main": [
        "dist/smart-table.js"
      ]
    }
```

**Comment by RoraxHan** [comment]
Thank you so much

**Comment by donli1210** [comment]
@daibangcanhcut Thanks so much! I have the same issue and it is solved now.

**Comment by roy651** [comment]
+1

**Comment by erweehong** [comment]
@daibangcanhcut thanks. I hit same issue and you save my day.

**Comment by Ankushjadon** [comment]
thanks, I have the same issue and it is solved now.
