### ISSUE TITLE
In mobile version background image is hidden by solid background with $body-bg color

### ISSUE THREAD

**Issue by shvydky** [akveo/blur-admin#36]
Can be fixed by comment one line in the following code but I'm not sure that this is correct:

File /blur-admin/src/sass/theme/_layout.scss:24  
```
body.mobile{
  background: none;
  .body-bg{
    display: block;
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    background-attachment: inherit;
    /*background-color: $body-bg;*/
  }
  &.blur-theme {
    @include main-background();
  }
}
```

To reproduce do the following steps:
1. Open http://akveo.com/blur-admin/#/dashboard in Chrome
2. Enable "Device mode" and choose iPhone 5 emulation
3. Refresh page and light-gray background will appear

**Comment by KostyaDanovsky** [comment]
@shvydky, thanks for the issue report
