### ISSUE TITLE
How to use gulp for creating a bundled web application

### ISSUE THREAD

**Issue by zestllankesh** [akveo/blur-admin#369]
Hi,

I browsed through issue section and couldn't find solution for my problem.

So I have couple of issues:

1. When I do **gulp serve:dist** the **release** folder does not include **app** folder
<img width="1280" alt="screen shot 2017-12-29 at 5 59 08 pm" src="https://user-images.githubusercontent.com/16576814/34437173-0d96fa82-ecc2-11e7-9777-d31c2d50e7d6.png">

2. The **gulp serve:dist** does not exit
<img width="466" alt="screen shot 2017-12-29 at 5 50 21 pm" src="https://user-images.githubusercontent.com/16576814/34437025-cec52b9a-ecc0-11e7-9903-dab8f25230c2.png">
 
3. When the **gulp serve:dist** is done building release it opens browser automatically. I am able to login, but the dashboard does not show up. I've attached screenshot of that.
<img width="1280" alt="screen shot 2017-12-29 at 5 49 24 pm" src="https://user-images.githubusercontent.com/16576814/34437031-d3fab468-ecc0-11e7-9130-b24fcca498da.png">

What I want to achieve is following:
1. When I do **gulp serve:dist** all the respective files and folders should get copied to **release** folder
2. Command should exit.

This is needed as I want to add it to my deployment script which is written in shell.
I have shared couple of screenshots for giving you the picture of what I want to do.

I am absolutely beginner to gulp. Have no clue what it does.
If you can guide me to create a gulp script from source code that will bundle my web app, it would be great.

I have not did not modify any gulp files present in **gulp** folder and **gulpfile.js**

Cheers,
Happy coding :)

**Comment by cmchecha** [comment]
Try with:
`gulp build`

**Comment by zestllankesh** [comment]
I tried gulp build. 
It still stalls.
Turns out I had to remove watch from build.js. After removing watch it stopped after building project.

Closing the issue as I found a workaround
