### ISSUE TITLE
Error "rangy-core.js:2971 Discontiguous selection is not supported." in device emulation mode

### ISSUE THREAD

**Issue by shvydky** [akveo/blur-admin#37]
Steps to reproduce:
1. Open http://akveo.com/blur-admin/#/dashboard
2. Enable device emulation
3. Refresh page

**Comment by KostyaDanovsky** [comment]
@shvydky, do you mean error in browser console? If yes, I cannot reproduce it. 
Could you give more details?

**Comment by shvydky** [comment]
Kostya,

Yes, error is shown in browser console.
In my environment error occurs for any device and any orientation.
I should investigate this deeply on my machine if you can't reproduce it.

**Comment by shvydky** [comment]
It's strange, but I can't reproduce this issue anymore.
