### ISSUE TITLE
i can't install it after gulp serve

### ISSUE THREAD

**Issue by kevinamrulloh** [akveo/blur-admin#372]
4@lokalhos MINGW64 /c/xampp/htdocs/Pro/66/blur-admin (master)
$ gulp serve
[12:21:12] Using gulpfile C:\xampp\htdocs\Pro\66\blur-admin\gulpfile.js
[12:21:12] Starting 'scripts'...
[12:21:13] Starting 'styles'...
[12:21:13] 'styles' errored after 75 ms
[12:21:13] Error: Cannot find module 'gulp-sass' from 'C:\xampp\htdocs\Pro\66\blur-admin'
    at Function.module.exports [as sync] (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\resolve\lib\sync.js:40:15)
    at requireFn (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\gulp-load-plugins\index.js:65:25)
    at Object.get [as sass] (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\gulp-load-plugins\index.js:108:41)
    at buildStyles (C:\xampp\htdocs\Pro\66\blur-admin\gulp\styles.js:58:13)
    at Gulp.<anonymous> (C:\xampp\htdocs\Pro\66\blur-admin\gulp\styles.js:20:10)
    at module.exports (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\orchestrator\index.js:134:8)
    at C:\Users\4\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
[12:21:13] gulp-inject 52 files into main.scss.
(node:27360) UnhandledPromiseRejectionWarning: Error: Error: jquery is not installed. Try running `bower install` or remove the component from your bower.json file.
    at C:\xampp\htdocs\Pro\66\blur-admin\node_modules\wiredep\wiredep.js:30:56
    at C:\xampp\htdocs\Pro\66\blur-admin\node_modules\wiredep\lib\detect-dependencies.js:149:29
    at C:\xampp\htdocs\Pro\66\blur-admin\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\lodash\lodash.js:3001:24)
    at C:\xampp\htdocs\Pro\66\blur-admin\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\lodash\lodash.js:9359:14)
    at detectDependencies (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\wiredep\lib\detect-dependencies.js:34:7)
    at wiredep (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\wiredep\wiredep.js:70:39)
    at DestroyableTransform._transform (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\wiredep\wiredep.js:136:34)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\Pro\66\blur-admin\node_modules\readable-stream\lib\_stream_transform.js:182:10)
(node:27360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:21:15] all files 252.78 kB
[12:21:15] Finished 'scripts' after 3.18 s

**Comment by kevinamrulloh** [comment]
npm install >>

> node-sass@3.13.1 install C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-gyp\bin\node-gyp.js rebuild --ve                                                           rbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\n                                                           ode_modules\\which\\which.js:13:12)\n    at F (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\which\\which.js:68:19)\n                                                               at E (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\which\\which.js:80:29)\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-a                                                           dmin-1.3.1\\node_modules\\which\\which.js:89:16\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\isexe\\index.js:4                                                           2:5\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:16                                                           6:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\no                                                           de_modules\\which\\which.js:13:12)\n    at F (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\which\\which.js:68:19)\n                                                               at E (C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\which\\which.js:80:29)\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-ad                                                           min-1.3.1\\node_modules\\which\\which.js:89:16\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\isexe\\index.js:42                                                           :5\n    at C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166                                                           :21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-gyp\lib\configure.js:483:1                                                           9)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-gyp\lib\configure.js:508:16                                                           )
gyp ERR! stack     at C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\Pro\\55\\blur-admin-1.3.1\\node_modules\\node-gyp\\bin\\no                                                           de-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\Pro\55\blur-admin-1.3.1\node_modules\node-sass
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN blur_admin@1.3.0 No repository field.
npm WARN blur_admin@1.3.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current:                                                            {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\4\AppData\Roaming\npm-cache\_logs\2018-01-16T02_31_17_394Z-debug.log

**Comment by chiu0602** [comment]
Install Python 2 and include it into your `PATH`, then run `npm install` again

**Comment by ak99372** [comment]
It would be nice if the installation manual (or readme) mentioned this project has dependency on Python.

**Comment by kevinamrulloh** [comment]
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.1             3.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win             32-x64-59_binding.node":

**Comment by kevinamrulloh** [comment]
i've download python27

**Comment by XBITSwitzerland** [comment]
@chiu0602 how can I inlcude python into path? I downloaded python-2.7.15

**Comment by kevinamrulloh** [comment]
solved 3 monts ago thanks

**Comment by XBITSwitzerland** [comment]
@kevinamrulloh I can't open the link

**Comment by XBITSwitzerland** [comment]
So I installed python 2.7.15 and included it into path. But I still get this error. What else do I have to do?

**Comment by kevinamrulloh** [comment]
@XBITSwitzerland im sorry, what error you got.?

**Comment by XBITSwitzerland** [comment]
@kevinamrulloh 
This is my full log:
$ npm install

> node-sass@3.13.1 install C:\github\blur-admin\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\github\blur-admin\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\github\blur-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\github\\blur-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\github\blur-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\github\blur-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\github\blur-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\github\blur-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\github\blur-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\github\blur-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\github\blur-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\github\blur-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\github\blur-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\github\blur-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\github\blur-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\github\blur-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\github\\blur-admin\\node_modules\\which\\which.js:13:12)\n    at F (C:\\github\\blur-admin\\node_modules\\which\\which.js:68:19)\n    at E (C:\\github\\blur-admin\\node_modules\\which\\which.js:80:29)\n    at C:\\github\\blur-admin\\node_modules\\which\\which.js:89:16\n    at C:\\github\\blur-admin\\node_modules\\isexe\\index.js:42:5\n    at C:\\github\\blur-admin\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files (x86)\Python27\python.EXE
gyp verb check python version `C:\Program Files (x86)\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.15\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.1
gyp verb build dir attempting to create "build" dir: C:\github\blur-admin\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\github\blur-admin\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\github\blur-admin\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\github\blur-admin\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\github\blur-admin\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Program Files (x86)\Python27\python.EXE
gyp info spawn args [ 'C:\\github\\blur-admin\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\github\\blur-admin\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\github\\blur-admin\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\danyb\\.node-gyp\\8.11.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\danyb\\.node-gyp\\8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\github\\blur-admin\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\danyb\\.node-gyp\\8.11.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\github\\blur-admin\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\github\\blur-admin\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\danyb\.node-gyp\8.11.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
Der Buildvorgang wurde am 02.05.2018 14:16:27 gestartet.
Projekt "C:\github\blur-admin\node_modules\node-sass\build\binding.sln" auf Knoten "1" (Standardziele).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Release|x64" wird erstellt.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f▒gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\github\blur-admin\node_modules\node-sass\build\binding.sln]
Die Erstellung des Projekts "C:\github\blur-admin\node_modules\node-sass\build\binding.sln" ist abgeschlossen (Standardziele) -- FEHLER.

Fehler beim Buildvorgang.

"C:\github\blur-admin\node_modules\node-sass\build\binding.sln" (Standardziel) (1) ->
(_src_\libsass Ziel) ->
  MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f▒gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\github\blur-admin\node_modules\node-sass\build\binding.sln]

    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:00.08
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\github\blur-admin\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\github\\blur-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\github\blur-admin\node_modules\node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN blur_admin@1.3.1 No repository field.
npm WARN blur_admin@1.3.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\danyb\AppData\Roaming\npm-cache\_logs\2018-05-02T12_16_28_974Z-debug.log

**Comment by kevinamrulloh** [comment]
i think manual download node sass
