### ISSUE TITLE
Error  ELIFECYCLE

### ISSUE THREAD

**Issue by pdvbalaji** [akveo/blur-admin#390]
Hello,
    I like your blur-admin and I download it for using typescript , when run 
I am getting below error 
**Please solved this problem** . I try in different ways but not get 
Please find attachment 

![blur-admin_error](https://user-images.githubusercontent.com/12511314/39248375-88565ef4-48b9-11e8-8d43-e840c3545184.png)

pm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:

**Comment by XBITSwitzerland** [comment]
I have the same error. Did you find a solution for this?
