### ISSUE TITLE
ui-router and submenu

### ISSUE THREAD

**Issue by ibbatta** [akveo/blur-admin#40]
Hi,

I want create a child page for a state in my sidebar, but i won't create submenu for that child, how I can do this? I really have to create a static content page?

```
$stateProvider
            .state('dashboard', {
                url: '/dashboard',
                templateUrl: 'app/pages/dashboard/dashboard.html',
                title: 'Dashboard',
                sidebarMeta: {
                    icon: 'ion-android-home',
                    order: 0,
                },
            })
           .state('dashboard.clients', {
                url: '/clients',
                controller: 'ClientsPageCtrl',
                controllerAs: 'vm',
                title: 'Clients',
                templateUrl: 'app/pages/clients/clientsTemplate.html',
                sidebarMeta: {
                    icon: 'ion-person-stalker',
                    order: 300
                },
            });
```

**Comment by KostyaDanovsky** [comment]
@ibbatta, please check out documentation about sidebar configuration: https://akveo.github.io/blur-admin/articles/051-sidebar/

**Comment by ibbatta** [comment]
@KostyaDanovsky I read the documentation but I can't find out how to create a child state without creating a submenu item. Is it possible? If so, how?

**Comment by KostyaDanovsky** [comment]
If you want to create state without affecting sidebar, you should remove `sidebarMeta` property from the your state.

**Comment by ibbatta** [comment]
In this way I can't show the menu-item by the way, am I right?
I want to show 1, 2 or more sidebar items (and relative children) without nesting each others.

**Comment by KostyaDanovsky** [comment]
@ibbatta, unfortunately it's not possible right now. 
But we always appreciate pull-requests for the new features.

**Comment by lugovsky** [comment]
@ibbatta Why configuring sidebar manually via `baSidebarServiceProvider` doesn't work for you btw?

**Comment by vazh** [comment]
@ibbatta did you mean, you need to make clients menu, but without making it into a sub menu right ?
if so, i actually found how to do it @ #53 .
you just have to specify parents in it.

**Comment by ibbatta** [comment]
@lugovsky is possible configure manually via `baSidebarServiceProvider` a child of a current sidebar menu item?

**Comment by ibbatta** [comment]
@vazh yes i found that solution too. Thanks 👍
