### ISSUE TITLE
Need documentation to work with services

### ISSUE THREAD

**Issue by manojakondi** [akveo/blur-admin#43]
Hi Team,

I am a beginner here and I need a documentation on how to work with services and controllers with this blur admin dashboard. It would be great if you respond asap.

Thanks

**Comment by manojakondi** [comment]
@lugovsky I'd really appreciate your help here

**Comment by lugovsky** [comment]
Hi @manojakondi,

Sorry for late reply. Our framework is based on AngularJs. You can refer to its documentation regarding that question. In particular, I suggest reading following article: https://docs.angularjs.org/guide/providers

Best regards,
Vlad
