### ISSUE TITLE
Black screen on close "compose mail"

### ISSUE THREAD

**Issue by VinniZP** [akveo/blur-admin#45]
http://akveo.com/blur-admin-mint/#/components/mail/inbox
Chrome 50 mac os

**Comment by vazh** [comment]
for me its not blackscreen,
its flickering, into black screen.
same case with another modal.

**Comment by lugovsky** [comment]
@VinniZP Thanks for reporting guys. I agree this is some strange behavior. We need to look into it

**Comment by lugovsky** [comment]
This was happening because angular-bootstrap was really outdated. Seems fixed now after I installed latest version and added it as a dependency
