### ISSUE TITLE
Chartist 0.9.7 compatibility

### ISSUE THREAD

**Issue by lugovsky** [akveo/blur-admin#5]
Originally we were using Chartist 0.9.5 version. Now when latest version is 0.9.7 page with charts look like this:

![Chartist js 0.9.7](https://cloud.githubusercontent.com/assets/2788046/14418370/aa91e8fa-ffc6-11e5-9305-dde9f4614b91.png)

**Comment by KostyaDanovsky** [comment]
We set 0.9.5 version by default for Chartist library, because starting from 0.9.6 version there is an issue  when loading charts the first time.
