### ISSUE TITLE
NPM Installation Issue

### ISSUE THREAD

**Issue by javahuat** [akveo/blur-admin#51]
1st time Nodes.js user. I can't seem to be able to install this package. Any expert here can help out?

I tried both node-v4.4.5 and node-v6.2.0.

![image](https://cloud.githubusercontent.com/assets/19710368/15746629/f18e464c-2909-11e6-94df-65bcbacdf250.png)

**Comment by vazh** [comment]
i always ignore the node-gyp error. since its always error because of the environment, though there's a guide on how to fix it. please check node-gyp project pages, or microsoft. both list the temporary fix for this kind of issue

**Comment by lugovsky** [comment]
Hi @javahuat,

As @vazh this is very common error and I ignore it as well. You might me interested in reading this thread: https://github.com/nodejs/node-gyp/issues/629

As well if still experiencing some issues running template you might be interested in downloading just HTML/JS/CSS files from here: http://akveo.github.io/blur-admin/articles/091-downloads/

**Comment by Shashwat78** [comment]
hello ,I have download code and run but facing issue is  missing start script please help me how so solve this error.

Thank you,
