### ISSUE TITLE
Missed checkmark

### ISSUE THREAD

**Issue by Semigradsky** [akveo/blur-admin#58]
![image](https://cloud.githubusercontent.com/assets/1198848/15805145/4e3988cc-2b29-11e6-9684-6d6a4fe6b1e8.png)

http://akveo.com/blur-admin/#/tables/smart
Google Chrome 51.0.2704.79 m
Windows 10

**Comment by lugovsky** [comment]
@Semigradsky Thanks a lot again! We're working on it. But yet again we would be very thankful for PRs
