### ISSUE TITLE
Incorrect title color in modal

### ISSUE THREAD

**Issue by shvydky** [akveo/blur-admin#62]
Modal title is white on white background:
![image](https://cloud.githubusercontent.com/assets/913609/15836340/faa46d34-2c3c-11e6-9b6c-41e63200662c.png)

Chrome: 50.0.2661.102 m

**Comment by shvydky** [comment]
Please, look also on colors for form inputs. Most of them has white text on white background.

**Comment by brijesh1ec** [comment]
MIssing thing is, how to load the login page.
1) Create the new module. app.page.login, file Login.module.js file,
2) create controller Login.controller.js file.
3) create services Login.Services.js file.
4) inculde this file in Index.html page.
it loads the Login page in UI-View under the content page,

ISSUE- Side bar and top navigation appreas, ideally login page should
render fully across the page.

Solution.
1) Create another root page or main page.
2) if Index.html is root page then main section should be moved to
main.html file
3) Create folder Main , create app.page.main mdoule in Main.module.js file,
same way add controller and services file.
4) Inject the app.page.Main module in app.page module and

5) Include this new .js files in Index.html files.
6) include UI-VIEW in index.html file,(if it is not there un named
ui-view). it will load the login page as full page.
7) on click of login Page user State.go('Main) state to go to main.html
file which is having main section with Side,Page top, top content and
another UI-VIEW. which will load the Side bar, page top, and content page,
on click of menu, it should open the views in content page.

ISSUE- it opens the views with parent UI-VIEW(index.html) not in child
view(Main.html).

There are two UI-Views (un named). one in Index.html page, another in
Main.html page.
how to load the views on click of side bar in content page(main.html). Why
it opens the views with Index.html page. Its really may be a bug or there
way to load the content inside child view(main.html).

total there are 3 UI-VIEW, a) Index.html for login page to render, b)
main.html to render the content,c) which loads submenu iteams( abstract
true).

In Blur admin there are two UI-VIEW which works fine, why it doesn't works
with 3 UI-VIEW.

Thanks,
Warm Regards :Brijesh Pal
Mobile : +919790752446
