### ISSUE TITLE
Is possible use blur-admin without node?

### ISSUE THREAD

**Issue by alexmod20** [akveo/blur-admin#64]
I haven't node and i can't install it, how i can use this framework? 
I must download each library and import them manually? 

Thanks.

**Comment by luqihang** [comment]
Due to the build tools depend on the node,you will not be to build the project without it.
Node.js can run on almost all of platform，try it again.

**Comment by alexmod20** [comment]
I can't install node for my reason not for platform, but if i add manually all library, the framework does work? Is there another way?

**Comment by vazh** [comment]
wait, so how did you run angular without nodejs in development mode ?

**Comment by alexmod20** [comment]
It's what I'm asking.

**Comment by vazh** [comment]
well, if you add the dependency manually, i mean all js. i'm sure you can.
it's literally the same, npm & gulp only make it easier since they will inject it automatically.

**Comment by lugovsky** [comment]
You can also download release and dev-release from here now: http://akveo.github.io/blur-admin/articles/091-downloads/
