### ISSUE TITLE
I have a trouble when i add new pages and directives

### ISSUE THREAD

**Issue by GentooXativa** [akveo/blur-admin#70]
Hi!

Im having some troubles when i compile and launch with **gulp serve:dist** or on a live enviroment.

[Developer tools image](http://i.imgur.com/vksKckB.png)

Everything works well on development enviroment or with **gulp serve**

What im doing wrong?

**Comment by lugovsky** [comment]
@GentooXativa You just might need to add semicolon after `.directive('serverEdit', serverEdit)`

**Comment by GentooXativa** [comment]
I tryed, and some different approaches. 

Always the same error

http://imgur.com/s89CsDE

**Comment by lugovsky** [comment]
This happens usually because of some missing semicolon, please search your code for some issues of this kind

**Comment by GentooXativa** [comment]
Ok, i go to search and try to fix. Thanks for your help

**Comment by GentooXativa** [comment]
Yeah, was a semicolon on another file, Thanks to JSLint :+1:
