### ISSUE TITLE
Possibility of Angular 2.0 based Theme?

### ISSUE THREAD

**Issue by bapatel1** [akveo/blur-admin#8]
@akveo,
This is really nice theme you've created. I would like to know if you have some future plan for Angular 2.0 based theme as well. Since many developers are using angular 2.0 Beta and new component based solutions, Is it possible to have this theme based on it?

Thanks & nice work!!

**Comment by lugovsky** [comment]
@bapatel1 Yes, it is one of possible scenarios, but so far we haven't made any decision

**Comment by bapatel1** [comment]
Thank you Vladimir, I appreciate your quick reply. Our organization starts making our new products in Angular 2.0 and I am sure many more companies do that as well , so I would like to see more and more themes and templates on Angular 2.0.

I will see if we can use your product in our old angular 1.0 base products sometime.

Thank you,

**Comment by lugovsky** [comment]
No problem, I will keep this issue open to see interest in Angular 2.0 version

**Comment by bapatel1** [comment]
Absolutely, I appreciate that. I will keep watching your project for future ref.

Thank you,

**Comment by jakeNiemiec** [comment]
+1

**Comment by atilkan** [comment]
+1

**Comment by orosandrei** [comment]
+1

**Comment by josephbisaillon** [comment]
+1

**Comment by blacksonic** [comment]
Is there a built css a can include after regular bootstrap css?
I would happily include this theme in my Angular 2 starter project
https://github.com/blacksonic/angular2-es6-starter

**Comment by wesleykaoru** [comment]
+1

**Comment by InfinityWebMe** [comment]
+1

**Comment by gambcl** [comment]
+1

**Comment by mayur-mi** [comment]
+1

Also templates in pug(previously known as jade) please. Love the structure. Great work.

**Comment by Vorlif** [comment]
+1

**Comment by karimrg** [comment]
+1

**Comment by alaj** [comment]
+1

**Comment by ZeBigDuck** [comment]
+1

**Comment by ksom** [comment]
👍

**Comment by anil826** [comment]
Hi Vladimir, 
It is possible to convert this template into Angular 2.0 I want to integrate this whole design in my new product.

**Comment by kboussebat** [comment]
+1

**Comment by reevader** [comment]
+1

**Comment by osixia** [comment]
+1

**Comment by ksom** [comment]
Maybe some interested persons don't know there is an issue for angular 2 version. I think it could be nice to put a mention with the issue link in the README. What do you think about that ?

**Comment by gfviegas** [comment]
+1

**Comment by sspilleman** [comment]
+1

**Comment by jimitndiaye** [comment]
+1

**Comment by nihique** [comment]
+1

**Comment by nnixaa** [comment]
Hey guys, thank you for waiting, today we've just released our first preview of angular 2 based admin template. Check it out here https://github.com/akveo/ng2-admin, as usual, your feedback is much appreciated!

**Comment by osixia** [comment]
:heart:

**Comment by karimrg** [comment]
looks great!, Thanks

**Comment by bapatel1** [comment]
Looks nice! Good work and thanks for considering my request :+1:

**Comment by bapatel1** [comment]
Do you want me to keep this issue running anymore or want me to close i guess?

**Comment by smartapant** [comment]
@bapatel1 We are happy you liked the result of our work, so now i will finally close the issue :)
