### ISSUE TITLE
Blur- Admin Passing values between pages

### ISSUE THREAD

**Issue by awii5** [akveo/blur-admin#82]
Hello,

How to pass values between pages ?

Below code in my controller.

$scope.delete = function (item) {         
		
		$.ajax('http://jsonplaceholder.typicode.com/posts/' + item.id, {
			  crossDomain: true,			  
			  method: 'Delete',			  
			}).then(function(data) {
			  window.location.href = '/#/myModule/layouts/' + data.id
			});
        }

In success it redirect to myModule/layouts/' but "id" value it dosent append.

Please let me know how to pass and access in module pages.
Thanks.

**Comment by lugovsky** [comment]
@awii5 We use UI router for routing. So I think you can look into its documentation. In particular you might be interested in this article: https://github.com/angular-ui/ui-router/wiki/URL-Routing#url-parameters

**Comment by awii5** [comment]
Thank u vry much lugovsky :)
