### ISSUE TITLE
gulp build always create 404, auth, reg

### ISSUE THREAD

**Issue by vazh** [akveo/blur-admin#83]
i already delete those 3 files. but when i run gulp build, it always get recreated.

**Comment by lugovsky** [comment]
@vazh I think you might need to remove `injectAuth` and `inject404` from your gulp build. In particular you can look at this line https://github.com/akveo/blur-admin/blob/master/gulp/inject.js#L18

**Comment by vazh** [comment]
ah, i see.
anyway, from what i understand. this project was generated by generator-gulp-angular right ?
is it an older version ? or did you heavily edit it ?
since i dont find eslint etc.

**Comment by vazh** [comment]
@lugovsky thanks, it definitely works.
not them same thing. but still the same kind of issue.
it recreates all those images from assets folder, even though i deleted all of them before.

**Comment by lugovsky** [comment]
@vazh Yes it was generated from `generator-gulp-angular`. We've added plenty editions as well.

As for your second question, I'm not sure why does it recreates all those images. I think if you delete them `src/assets`, they should be removed completely. Are you able to provide more information please?

**Comment by vazh** [comment]
@lugovsky sorry, not right now. i'll test more later. probably because i forgot to delete release folder.
im closing this issue right now.

thanks, cheers.
