### ISSUE TITLE
different result with gulp-serve & gulp-serve:dist / gulp-build

### ISSUE THREAD

**Issue by vazh** [akveo/blur-admin#84]
this kind of similar to #80 .

why do i get different result between `gulp serve` and `gulp serve:dist` or `gulp build`
gulp serve works fine, while build/serve:dist make a whole lot of error that it consume my processor to 100% and i cant do debugging on it with developer tools.

please help, thanks.

**Comment by lugovsky** [comment]
Hi @vazh 

Could you please share the errors you're getting? 

In any case `serve:dist` and `build` is actually configurations to run script concatenation/minification and sourcemaps build which obviously take CPU time. As well as scripts are minified and concatenated, you can only debug them using sourcemaps.

In any case le me know what error you see and I will look.

P.S. Really appreciate your help in issues! Many thanks!

**Comment by vazh** [comment]
unfortunately, i cant even open developer tools, since the error keeps appearing, and it consume all of my processor. so i have to force close it so it can go back to normal.

anyway, i'll just explain what i do to get those error. since right now, i kind of fixed it already.

so, for start, i did not follow your guide on how to make a new page, since i was a lazy guy.
so i just dump all of my files from my previous template which is only bootstrap+ui.bootstrap. which is sucks that i can only make a navbar. lol.

and then i include `BlurAdmin.theme` into my module definition file. 
which so far, works great with `gulp serve` but then everything falls apart when i try to `gulp build` or `gulp serve:dist` somehow it can't find the html files that are supposed to be minified and concatenated.

but right now, it works okay-ish.
1. i don't change module name
2. i put my previous project files inside pages folder
3. i change those files module name into `BlurAdmin.pages`

a few issues i found after `gulp serve:dist` or `gulp build` is, the bootstrap glyphicon files didn't exist inside fonts folder. and i use `angular-datatables` but the sort icon is missing too. but then i just need to paste those files into its folders.

haven't done any research on what cause the main issue with my 1st post.
either the placement have to be inside pages folder, or module name too.
need to wait till i got time to tinker with it again. got a deadline to make :).

P.S. the pleasure is all mine, kind of happy to see a free angular admin template. 
great job guys :+1:

**Comment by lugovsky** [comment]
Well I think it should be some configuration issue, maybe gulp is configured in the way that it encounters some infinite filesystem loop. I really don't know, but I think you can fix that when you have time.

As for fonts problem, this commit should fix that f53c360d3023cc1e29734e5a5ea827b5cdb698f0

**Comment by vazh** [comment]
@lugovsky well the thing is, previously i use generator-gulp-angular as my base generator. those works fine. so i thought, hey this one use the same thing. then just dump all my files into app folder.

f53c360 yeah, 3 days ago i was busy finding ways to fix those problem, havent seen that before posting my reply. thanks. will have to try that later.

i'll close this and let you know what causes this later.

**Comment by majkelo** [comment]
I faced the same error. Here is the solution:
https://gist.github.com/majkelo/1fcacd3aea7c00ad2e31e2fdf696b5e9
