### ISSUE TITLE
Missing .eslintrc config file

### ISSUE THREAD

**Issue by huguangju** [akveo/blur-admin#94]
I saw in the `script` gulp task used `gulp-eslint` plugin, but can not found any .eslintrc config file in the project

**Comment by vazh** [comment]
yeah, no linting in there. maybe you can try generate .eslintrc from Swiip/generator-gulp-angular

**Comment by huguangju** [comment]
Ok, thank you. Maybe need add a instructions about this to document.

**Comment by Alderian** [comment]
Hi,

  So, no .eslintrc will be provided? I might fork and branch and make a pull request with one of mine.

  I noticed that running eslinter with suggested config throws a lot of errors.. more than 5000

Thanks
