### ISSUE TITLE
[Q] need somehelp about sass

### ISSUE THREAD

**Issue by vazh** [akveo/blur-admin#96]
so currently, my apps route kinda looks like this

- login
- app
  - ...
  - ...
  - ...
- etc.

the login are placed at top level routing.
i want to reproduce your login.html into those route. i kind of messing around a bit. copy & paste auth.scss files and then rename it into login.scss.
it works great, but then again, it changes styles for app path too. like the background changing etc. it follow auth.scss files style.
can you point out as to how to make it only change the styles for login route ?

sorry, no example right now. only words.

**Comment by lugovsky** [comment]
Quick solution would be to use some wrapper class for the whole login page I guess

**Comment by vazh** [comment]
well the thing is, i dont know much about css, more about its preprocessors.
either less or sass. i'm suck at it. very much.

after i add some wrapper class, then what do i have to do ?
add wrapper class name in front of every lines inside login.scss files ?

**Comment by lugovsky** [comment]
In `login.scss` wrap everything inside of:
```scss
.login-page-wrapper {

}
```

in your template for login route wrap everything inside of `<div class="login-page-wrapper"></div>`

**Comment by vazh** [comment]
wait, you can do it like that ? oh wow that's nice. thanks again. will try it later, again.
:+1:

**Comment by vazh** [comment]
@lugovsky thanks a lot, it works perfectly.
unfortunately, the auth-main & auth-block stays at the top, did not go to the middle of the screen.
![image](https://cloud.githubusercontent.com/assets/3176112/16439119/ce3384ec-3ddf-11e6-9c8c-aadfca18a55b.png)

**Comment by lugovsky** [comment]
This is a great article about centering objects: https://css-tricks.com/quick-css-trick-how-to-center-an-object-exactly-in-the-center/ Hope it will help

**Comment by vazh** [comment]
@lugovsky thanks, much appreciated.
closing this.

**Comment by ashishc** [comment]
Hi I am just wondering if there is any way to use gif image on loading screen.
